[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyAk_M5fkYdXhjynWvKWGlPek_2Za90ZIB4"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "markaz-abdullah-bin-mubarak.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "markaz-abdullah-bin-mubarak"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "markaz-abdullah-bin-mubarak.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "254933105084"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:254933105084:web:6697047e3ee1fe33efd3b9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/"
  to = "/en"
  status = 301
  force = true
